import { Container, useTheme } from '@mui/material'
import Grid2 from '@mui/material/Unstable_Grid2'
import AsideList from 'feature/aside-list'
import ListItemType from 'feature/aside-list/types/list-item.type'
import Form from 'feature/form'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'

const Home: NextPage = () => {
  const [currentMenuItem, setCurrentMenuItem] = useState<ListItemType | null>();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth='md' sx={{ minHeight: '100vh' }}>
        <Grid2 container spacing={3} padding={5}>
          <Grid2 width='100%' md={4}>
            <AsideList currentMenuItem={currentMenuItem} setCurrentMenuItem={setCurrentMenuItem} />
          </Grid2>
          <Grid2 width='100%' md={8}>
            <Form currentMenuItem={currentMenuItem} title={currentMenuItem?.name} />
          </Grid2>
        </Grid2>
      </Container>
    </>
  )
}

export default Home
